server/api/index.js
I wanted to add a trivial change. @mesi17
=> trival change

Norms/norms.md
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> Add Team Norms

package-lock.json, server/db/models/index.js, server/db/models/product.js
=> feat(models/product): creates product model-#9

script/seed.js, server/api/users.spec.js, server/db/models/user.js, server/db/models/user.spec.js
Updated the User model from the default to include firstName and lastName.
=> feat(models/users) added some columns to the preexisting user model-#8

package-lock.json, server/db/models/index.js, server/db/models/order.js
=> feat(models/order) created order model-#11

server/db/models/index.js, server/db/models/orderProduct.spec.js, server/db/models/orderproduct.js
=> closes #10

server/api/index.js, server/api/products.js
Hooks in a products router into the api directory.
=> feat(routes/products) added a product route- closes #13

package-lock.json, script/seed.js, server/db/models/product.js
add(seed): added products to seed file
=> closes #20

server/api/products.js
Adds a route for getting a single product.
=> feat(routes/products) added get route for single product -closes #14)

client/store/allProducts.js
made an allProducts initial state, action creator, thunk creator, and reducer
=> allProducts create(reducer), create(creators) closes #33 closes #34

script/seed.js, server/db/models/product.js
Changed the data type for price inside the products model. Now it can accept amounts larger than $9.99.
=> fix(models/product) updated validation on price -closes #25

.travis.yml
=> chore(heroku): send token to travis closes #15

.travis.yml
=> fix(heroku): added api_key closes #15

package-lock.json, package.json
updated lodash because github said so.
=> chore(security): updating lodash dependency - #47

client/store/allProducts.spec.js, client/store/index.js
Test for products store:
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> test(store/products): test for products store closes #54

server/api/products.spec.js
test for testing all products route
=> test(routes/products): all products route test closes #53

client/components/Cart.js, client/store/orderProduct.js, client/store/orders.js, server/api/orders.js
created order checkout api. Created info form on cart component. Checkout button can handle submitting the form and updating the database.
=> feature(checkout): created checkout api, checkout button handles submit closes-#75

client/components/navbar.js, client/routes.js
Added nav buttons for getting to the cart and to the products. Made seeing the products the home page.
=> feat(nav): added navigation and changed home page – closes #78

client/components/single-product.js
Added an alert when an item is added to the cart.
=> fix(add-to-cart): added alert when item added to cart – closes #81

client/components/Cart.js
Fixed the cart so it's contents load without the user having to refresh.
=> fix(cart): made cart contents load before refresh – closes #80

client/components/navbar.js
changed Boilemaker to ProDucks
=> fix(title): changed navbar title

client/components/cart-by-any-other-name.js, client/routes.js, client/store/orderProduct.js, server/api/orderProducts.js
User can now change the quantity of an item in her cart and see the results in real time.
=> feat(user cart): user can edit quantity of items in cart, closes #94

client/components/cart-by-any-other-name.js, client/store/orderProduct.js, server/api/orderProducts.js
=> feat(cart/delete): Logged in users can delete cart items closes #98

client/components/cart-by-any-other-name.js, client/store/orderProduct.js, server/api/orderProducts.js
Guests can edit their cart on local storage
=> Feat(guest cart/ edit): Guests can edit their cart closes #101

client/components/single-product.js, public/style.css
=> feature(css): css for single product

client/components/cart-by-any-other-name.js, client/components/single-product.js
Ability to delete items from guest cart on local storage
=> Feat(guest cart/delete): Delete items in the guest cart closes #103

client/components/cart-by-any-other-name.js, client/components/single-product.js, client/store/orders.js, package-lock.json, package.json, public/index.html, public/style.css
Instead of alerts, we now have toast notifications (toastr node module).
ALSO, we rewired the checkout procedure to go through redux instead of working entirely within the cart component.
=> feat(toast notifications): replaced alerts with toasts, closes #106

client/components/cart-by-any-other-name.js
changed cart total cost to multiply by quantity and round
=> fix(cart): fix cart total cost

client/components/cart-by-any-other-name.js, client/components/single-product.js
adjusted position of toast notification
=> Feat(UI/toast notifications): adjusted position of toast notification
